/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = [
    'abilities',
    'createdAt',
    'expiresAt',
    'hash',
    'id',
    'lastUsedAt',
    'name',
    'tokenableId',
    'type',
    'updatedAt',
  ] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'email',
    'fullName',
    'id',
    'password',
    'updatedAt',
    'role',
  ] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare Role: 'admin' | 'user' | 'finance' | 'manager'
}

export class ClientSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'email', 'updatedAt'] as const
  $columns = ClientSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare email: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProductsSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'amount', 'updatedAt'] as const

  $columns = ProductsSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare amount: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class GatewaysSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'updatedAt', 'is_active', 'priority'] as const
  $columns = GatewaysSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column
  declare is_active: boolean
  @column
  declare priority: number
}


export class transactionsProductsSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'product_id', 'transaction_id', 'quantity', 'updatedAt'] as const
  $columns = transactionsProductsSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true})
  declare id: number
  @column()
  declare product_id:
  @column()
  declare transaction_id:
  @column()
  declare quantity: number
  @column.dateTime({ autoCreate: true, autoUpdate: true})
}


export class TransactionsSchema extends BaseModel {
  static $columns = ['amount', 'client', 'createdAt', 'gateway', 'id', 'status', 'external_id', 'updatedAt', 'card_last_numbers'] as const
  $columns = TransactionsSchema.$columns
  @column()
  declare amount: number
  @column()
  declare client: ClientSchema
}


